/* ============================================================
   events-data.js — single source of truth for all event info.
   Used by: index.html (featured), events.html (full listing),
   register.html (event <select> options).
   ============================================================ */

const VERTEX_EVENTS = [
  {
    id: "hacknova-24",
    title: "HackNova 24",
    category: "hackathon",
    catLabel: "Hackathon",
    date: "2026-08-12",
    dateLabel: "Aug 12, 2026",
    time: "9:00 AM \u2013 9:00 PM",
    venue: "Innovation Lab, Block C",
    seats: "40 seats left",
    desc: "A 12-hour build sprint where teams ship a working prototype from a single overnight prompt. Mentors, pizza, and a demo stage at the end.",
  },
  {
    id: "codesprint-arena",
    title: "CodeSprint: Algorithm Arena",
    category: "hackathon",
    catLabel: "Competitive Coding",
    date: "2026-08-20",
    dateLabel: "Aug 20, 2026",
    time: "2:00 PM \u2013 5:00 PM",
    venue: "Seminar Hall 2",
    seats: "openregistration",
    desc: "A timed, ICPC-style problem set for solo coders. Live leaderboard projected on the main screen for the full three hours.",
  },
  {
    id: "techtalks-ai",
    title: "TechTalks: AI in Industry",
    category: "talk",
    catLabel: "Guest Talk",
    date: "2026-09-03",
    dateLabel: "Sep 3, 2026",
    time: "11:00 AM \u2013 1:00 PM",
    venue: "Main Auditorium",
    seats: "120 seats left",
    desc: "Engineers from three regional tech companies talk through how applied AI actually gets shipped, monitored, and maintained in production.",
  },
  {
    id: "roborumble",
    title: "RoboRumble",
    category: "robotics",
    catLabel: "Robotics Showdown",
    date: "2026-09-15",
    dateLabel: "Sep 15, 2026",
    time: "10:00 AM \u2013 4:00 PM",
    venue: "Robotics Arena, Block D",
    seats: "18 teams left",
    desc: "Bots built by student teams face off in an obstacle-and-combat course. Open to spectators all day, entries close a week prior.",
  },
  {
    id: "design-jam",
    title: "Design Jam: UX Sprint",
    category: "design",
    catLabel: "Design Sprint",
    date: "2026-09-28",
    dateLabel: "Sep 28, 2026",
    time: "1:00 PM \u2013 6:00 PM",
    venue: "Design Studio, Block B",
    seats: "open registration",
    desc: "Small teams take a real campus problem from sketch to clickable prototype in one afternoon, judged by faculty and alumni designers.",
  },
  {
    id: "cyberquest-ctf",
    title: "CyberQuest: CTF Challenge",
    category: "security",
    catLabel: "Capture the Flag",
    date: "2026-10-10",
    dateLabel: "Oct 10, 2026",
    time: "9:00 AM \u2013 6:00 PM",
    venue: "Cyber Lab, Block C",
    seats: "30 seats left",
    desc: "Jeopardy-style capture-the-flag across web, crypto, forensics, and reverse engineering categories. Beginner track included.",
  },
  {
    id: "startup-pitch",
    title: "StartUp Pitch Night",
    category: "startup",
    catLabel: "Pitch Night",
    date: "2026-10-22",
    dateLabel: "Oct 22, 2026",
    time: "5:00 PM \u2013 8:00 PM",
    venue: "Innovation Lab, Block C",
    seats: "12 slots left",
    desc: "Student founders pitch to a panel of alumni investors for seed funding and mentorship. Open floor for audience Q&amp;A after each pitch.",
  },
  {
    id: "open-source-day",
    title: "Open Source Day",
    category: "hackathon",
    catLabel: "Community",
    date: "2026-11-05",
    dateLabel: "Nov 5, 2026",
    time: "10:00 AM \u2013 3:00 PM",
    venue: "Seminar Hall 1",
    seats: "open registration",
    desc: "A guided day of making your first real contribution to an open-source project, with maintainers on hand to review pull requests live.",
  },
];

const CATEGORY_ICONS = {
  hackathon: "\u2318",
  talk: "\u25CE",
  robotics: "\u2699",
  design: "\u25C7",
  security: "\u25B2",
  startup: "\u25CF",
};
